### PR TITLE
Fix Twitter Terms of Service and Privacy Policy

### PR DESCRIPTION
**Pull request by clementbiron**

### CODE REVIEW

**Comment by MattiSG** [comment]
@martinratinaud do you have time to review this?

**Review by MattiSG — CHANGES_REQUESTED** [review]
This would track both the “upcoming” and “present” terms of Twitter.
The upcoming terms are at the top, with a “Cette version des Conditions d’utilisation entrera en vigueur le 10 juin 2022” warning. The current ones are under “Présentes Conditions d’utilisation de Twitter — En vigueur jusqu’au 10 juin 2022”. There is a `#current` anchor right above it that could make it easy to target — even though we should anticipate that it disappears on June 10…

**Comment by clementbiron** [comment]
Although it is a bit beyond the promise of OTA, it seems to me little (or less costly) to follow the future ToS.
Also :
- we could detect interesting changes on the future ToS 
- we could detect changes between the future ToS and the implementation on the 10th
- it will take a maintenance intervention on June 10th to edit the declaration

**Comment by MattiSG** [comment]
I agree with all of your points. However, I believe the suggested tracking goes against the core value proposition of Open Terms Archive. Indeed:

1. We record a new version that is actually not a new version of the ToS but a record that contains two versions of the same document.
2. The diff becomes meaningless (it starts with +100 additions).
3. The metadata will be wrong: we will have one change on the 11th of May and one in a few months, when Twitter removes their old version from their page; yet likely no change recorded on the 10th of June, upon actual entry of the new terms. The number of changed lines will also be wrong. Indeed, the changes between the two versions are [minor](https://www.diffchecker.com/JCeMttEH). Yet, we will record a +100 lines change because of document duplication.

I agree that quite a few services also announce and publish their upcoming terms in advance, and that Open Terms Archive would benefit from offering a “future” feature instead of looking at the present and the past. But such a feature needs significant design to work properly. Until such work is done, I believe it is more important to ensure that we track properly documents as of their date of validity 🙂

**Comment by martinratinaud** [comment]
I agree with @MattiSG. the "future" feature should be thought carefully.

**Comment by martinratinaud** [comment]
I've rebased and ran lint, seems fine by me

**Review by martinratinaud — APPROVED** [review]

**Comment by clementbiron** [comment]
@MattiSG I made the changes to select only the current documents.

**Review by MattiSG — APPROVED** [review]
Thanks @clementbiron & @martinratinaud!

**Pull request merged**
