### PR TITLE
Fix facebook

### LINKED ISSUE #154: Filter footer from Facebook Terms of Service
See:

- https://github.com/OpenTermsArchive/france-elections-versions/commit/8a14c706f5a10a8c973cf173af0761b53b2decbf
- https://github.com/OpenTermsArchive/france-elections-versions/commit/41af8ca97b9c3a515e84b062bd19a68b44cc71dc
- https://github.com/OpenTermsArchive/france-elections-versions/commit/83e2765ab63e036b8c73e9690b002eb7f8a9a758

### PR DESCRIPTION
**Pull request by martinratinaud**
Remove footer from privacy policy and terms of service to close #154  and #151

### CODE REVIEW

**Comment by martinratinaud** [comment]
Sorry @martinratinaud I merged this by mistake before your review.
Please let me know if you think something was wrong

**Comment by MattiSG** [comment]
- I am surprised that the Privacy Policy was wrong since the 20th of June. Are you sure about the date for that history entry?
- I am surprised that the ToS change should be taken into account only from the 18th of August when I reported #154 already on the 11th. Are you sure about the date for that history entry?
- I notice that there are two `[role="separator"]` in the DOM. Are you sure about that selector?

**Comment by martinratinaud** [comment]
@MattiSG 

- Well, according to the [recorded versions](https://github.com/OpenTermsArchive/france-elections-versions/commits/main/Facebook/Privacy%20Policy.md) for this document, the last one available was on June the 20th. I'm calculating this automatically as the main date when selectors seem to have stopped working.
Though, this is not accurate as in this particular case, version was just unchanged during the period June 20 to July 13 when it was [reported as broken](https://github.com/OpenTermsArchive/france-elections-declarations/issues/151)

For the record, we've talked about this with @Ndpnt and we need to find a way to calculate these dates automatically as retrieving them manually is too time consuming.
For this, some ideas are
- retrieving the last working version
- retrieve all the subsequent snapshots and filter them to see if they give the same version
- retrieve the date of the first different version

But I recall this was not sufficient. ping @Ndpnt for more infos and this should become a OTA core issue

- For this date again, I used the last registered version which I agree is not accurate.
In this particular case, though, it appears to me that validUntil should not even be what you proposed but the exact date of change commit, as selector is valid until this date, just not stripping all content.
As date of commit was `2022-08-18T14:19:02.000Z` and date used is `2022-08-18T10:30:43+04:00` I think we should keep it

- This is indeed a tricky selector and it has been working like that when I tested on my local. Facebook DOM is really difficult to parse and that's the only selector that felt not supposed to change. If you can propose something else, please fell free, I'd be glad to amend it.

Here is a PR that changes the date https://github.com/OpenTermsArchive/france-elections-declarations/pull/163

**Comment by MattiSG** [comment]
> we need to find a way to calculate these dates automatically

I remember that the conclusion was that it is technically not possible to find that date in a fully automated way, and that even finding the best approximation takes a lot of work; that is why we did not prioritise that yet.

> validUntil should not even be what you proposed but the exact date of change commit, as selector is valid until this date, just not stripping all content.

The selector is “valid” in the sense that it works, but the generated version is not so “valid” as it contains content that should be filtered out. In my view, the footer should never have been there in the first place. The first commit in which it leaked is https://github.com/OpenTermsArchive/france-elections-versions/commit/e7b90bafa4eff32fe79699b5a9c69f33b5b3ecfc, dated 2022-04-27.
Maybe the simplest is to just check if the selector we use to remove the footer is problematic on snapshots before that date; if not, then we just add it in the declaration from the beginning, without a need to add it at some point in the history only. If it is problematic, then it should at least be added to prevent that specific version from being created.

**Comment by martinratinaud** [comment]
@MattiSG I found another way to have the best date (and actually the good one IMO)

I now check the declaration repository on Github and check if there is an open issue for this document.
In case, there is, I check for the latest comment mentioning an error happened and get its creation date.

I believe this is very accurate and easy to automate (just did it on my local contribution tool)

What do you think?

**Comment by MattiSG** [comment]
Yes, this sounds accurate under the following conditions:

1. The error that is corrected is not a blink.
2. There were no instance-wide errors such as DNS failures that would impact the reliability of the date.
3. The correction that is made did generate an issue.

For example, this would not work for #154.

**Comment by martinratinaud** [comment]
Thanks for the feedback, I will keep that in mind when I try to release the update feature on the contribution tool

**Pull request merged**
